version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - 'pr: dependencies'
    groups:
      # Note: React is a peer dependency of Docusaurus.
      docusaurus-and-react:
        patterns: ['@docusaurus/*', 'react', 'react-dom']
      development-dependencies:
        dependency-type: 'development'
        exclude-patterns:
          - '@docusaurus/*'
          - 'stylelint'
          - 'stylelint-config-standard'
          - 'eslint'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - 'pr: dependencies'
